### ISSUE TITLE
Cannot CTRL + C non-secure listener if secure publisher is publishing

### ISSUE THREAD

**Issue by sloretz** [ros2/sros2#54] opened 2018-06-22 17:04 UTC
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binaries
- Version or commit hash:
  - https://ci.ros2.org/view/packaging/job/packaging_windows/1043/
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

First confirm that `CTRL` + `c` works if no secure publishers are publishing
```
$ ros2 run demo_nodes_py listener
Traceback (most recent call last):
  File "C:\dev\ros2-windows\lib\demo_nodes_py\listener-script.py", line 11, in <module>
    load_entry_point('demo-nodes-py==0.4.0', 'console_scripts', 'listener')()
  File "C:\dev\ros2-windows\Lib\site-packages\demo_nodes_py\topics\listener.py", line 40, in main
    rclpy.spin(node)
  File "C:\dev\ros2-windows\Lib\site-packages\rclpy\__init__.py", line 108, in spin
    executor.spin_once()
  File "C:\dev\ros2-windows\Lib\site-packages\rclpy\executors.py", line 519, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "C:\dev\ros2-windows\Lib\site-packages\rclpy\executors.py", line 505, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "C:\dev\ros2-windows\Lib\site-packages\rclpy\executors.py", line 411, in _wait_for_ready_callbacks
    _rclpy.rclpy_wait(wait_set, timeout_nsec)
KeyboardInterrupt
```

In another terminal start `talker` with security enabled

```bat
set ROS_SECURITY_ROOT_DIRECTORY=%cd%/demo_keys
set ROS_SECURITY_ENABLE=true
set ROS_SECURITY_STRATEGY=Enforce
ros2 run demo_nodes_py talker
```

Restart the listener and try to interrupt it by pressing `CTRL` + `c`.
```
$ ros2 run demo_nodes_py listener
```

#### Expected behavior

`listener` would be interrupted when `CTRL` + `c` is hit

#### Actual behavior

`listener` does not respond to `CTRL` + `c` events at all. Process must be killed using task manager.

#### Additional information

`ros2 run demo_nodes_cpp listener` does not show the same behavior. I have not tested with other RMW implementations.

**Comment by mikaelarguedas** [comment] 2018-07-10 01:33
@sloretz Does the same happen with Connext or is this specific to Fast-RTPS ?

**Comment by sloretz** [comment] 2018-07-11 18:23
@mikaelarguedas On my VM I'm unable to test this at the moment. Using https://ci.ros2.org/view/packaging/job/packaging_windows/1060/ I'm unable to `CTRL` + `c` a listener at all, so I can't tell if the behavior changes when a secure publisher starts.

**Comment by sloretz** [comment] 2018-07-11 18:36
@mikaelarguedas I'm unable to reproduce this issue using fastrtps on `windows_portable`.

It seems like there are a lot of strange `CTRL` + `c` issues on just my VM (like ros2/rclpy#195). It may not be worth our time to investigate. What do you think about closing for now, and reopening if someone else is able to reproduce?

**Comment by mikaelarguedas** [comment] 2018-07-12 23:28
unable to reproduce on fresh install. closing for now and we can reopen if it reappears

**Closed by mikaelarguedas** 2018-07-12 23:28 UTC
Labels: bug
